# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [1]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [ ]:
#todo: 

# se utiliza el metodo arange para la creación de la lista 
arr=np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [ ]:
#todo:

# se crea una variable que crea la lista de ceros utilizando el método zeros
arr_ceros=np.zeros(5)

print(f"lista de ceros: {arr_ceros}")

# se accede al ínidice n°2 y se lo modifica a un 5
arr_ceros[2]=5
print(f"lista de ceros modificada: {arr_ceros}")

lista de ceros: [0. 0. 0. 0. 0.]
lista de ceros modificada: [0. 0. 5. 0. 0.]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [11]:
#todo: 

arr_random=np.random.randint(0,2,(3,3))
print(arr_random)

[[1 0 1]
 [1 1 1]
 [1 0 1]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [ ]:
#todo:

arr_ejemplo = np.array([10, 20, 30, 40, 50])
# creé una variable donde almaceno la lista sumada y la muestro
ejemplo_sumado=arr_ejemplo+5
print(ejemplo_sumado)
    
# genero un número aleatorio y lo multiplico elemento a elemento
num_random=np.random.randint(0,11)
ejemplo_multi=arr_ejemplo*num_random
print(ejemplo_multi)

[15 25 35 45 55]
[ 50 100 150 200 250]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [16]:
#todo:

arr_unos=np.eye(4)
print(arr_unos)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [ ]:
#todo: 

